export default class BaseControl {
    parent: any;
    object: any;
    property: any;
    initialValue: any;
    domElement: HTMLElement;
    $name: HTMLDivElement;
    static nextNameID: any;
    $widget: HTMLDivElement;
    $elForDisable: any;
    _disabled: boolean;
    _hidden: boolean;
    _name: any;
    _onChange: any;
    _changed: boolean;
    _onFinishChange: any;
    _listening: boolean;
    _listenCallbackID: any;
    _listenPrevValue: any;
    constructor(parent: any, object: any, property: any, className: any, elementType?: keyof HTMLElementTagNameMap);
    name(name: any): this;
    onChange(callback: any): this;
    _callOnChange(): void;
    onFinishChange(callback: any): this;
    _callOnFinishChange(): void;
    reset(): this;
    enable(enabled?: boolean): this;
    disable(disabled?: boolean): this;
    show(show?: boolean): this;
    hide(): this;
    options(options: any): any;
    setMin(min: any): this;
    setMax(max: any): this;
    setStep(step: any): this;
    setDecimals(decimals: any): this;
    listen(listen?: boolean): this;
    _listenCallback(): void;
    getValue(): any;
    setValue(value: any): this;
    update(): this;
    load(value: any): this;
    save(): any;
    destroy(): void;
}
