import ToggleControl from './controls/toggle-control';
import ColorControl from './controls/color-control';
import FunctionControl from './controls/function-control';
import NumberControl from './controls/number-control';
import OptionControl from './controls/option-control';
import TextControl from './controls/text-control';
import './rad-gui.css';
import BaseControl from './controls/base-control';
export declare class GUI {
    parent: GUI;
    autoPlace: boolean;
    width: any;
    closeFolders: boolean;
    injectStyles: boolean;
    touchStyles: boolean;
    root: any;
    children: any[];
    controllers: any[];
    folders: any[];
    domElement: HTMLDivElement;
    $title: HTMLButtonElement;
    $children: HTMLDivElement;
    container: HTMLDivElement;
    _closed: boolean;
    _hidden: boolean;
    _onChange: any;
    _onFinishChange: any;
    _onOpenClose: any;
    _title: string;
    _closeFolders: boolean;
    _onFinishChangeCallback: any;
    _onChangeCallback: any;
    _onOpenCloseCallback: any;
    constructor({ parent, autoPlace, container, width, title, closeFolders, injectStyles: shouldInjectStyles, touchStyles }?: any);
    add<T, K extends keyof T>(object: T, property: K): NumberControl | ToggleControl | TextControl | FunctionControl;
    add<T, K extends keyof T>(object: T, property: K, options: T[K][] | Record<string, T[K]>): OptionControl;
    add<T, K extends keyof T>(object: T, property: K, min: number, max: number): NumberControl;
    add<T, K extends keyof T>(object: T, property: K, min: number, max: number, step: number): NumberControl;
    addColor<T, K extends keyof T>(object: T, property: K, rgbScale?: number): ColorControl;
    addFolder(title: string): GUI;
    load(obj: any, recursive?: boolean): this;
    remember(...args: any[]): void;
    save(recursive?: boolean): {
        controllers: {};
        folders: {};
    };
    open(open?: boolean): this;
    close(): this;
    _setClosed(closed: any): void;
    show(show?: boolean): this;
    hide(): this;
    openAnimated(open?: boolean): this;
    title(title: any): this;
    reset(recursive?: boolean): this;
    onChange(callback: any): this;
    _callOnChange(controller: any): void;
    onFinishChange(callback: any): this;
    _callOnFinishChange(controller: any): void;
    onOpenClose(callback: any): this;
    _callOnOpenClose(changedGUI: any): void;
    destroy(): void;
    controllersRecursive(): any[];
    foldersRecursive(): unknown[];
}
export declare class RadGUI extends GUI {
    constructor(options?: any);
    addFolder(title: string): RadGUI;
    addButton(title: string, callback: () => void): FunctionControl;
    addColor<T, K extends keyof T>(object: T, property: K, rgbScale?: number): ColorControl;
    addNumber<T, K extends keyof T>(object: T, property: K): NumberControl;
    addNumber<T, K extends keyof T>(object: T, property: K, min: number, max: number): NumberControl;
    addNumber<T, K extends keyof T>(object: T, property: K, min: number, max: number, step: number): NumberControl;
    addToggle<T, K extends keyof T>(object: T, property: K): ToggleControl;
    addOption<T, K extends keyof T>(object: T, property: K, options: T[K][] | Record<string, T[K]>): OptionControl;
    addText<T, K extends keyof T>(object: T, property: K): TextControl;
    remove(controller: BaseControl): void;
    reset(recursive?: boolean): this;
}
export default GUI;
